# Generated by Django 3.1.3 on 2020-11-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201110_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.TextField(),
        ),
    ]
